# vpc parameters
vpc_cidr: "172.16.0.0/12"
vpc_name: "VPC_From_Demo"
vpc_description: "Create a new VPC resource for interview."
# aliyun location
alicloud_region: cn-shanghai
alicloud_zone: cn-shanghai-a
# vswitch parameters
vswitch_cidr: "172.16.1.0/24"
vswitch_name: "VSwitch_From_Demo"
vswitch_description: "Create a new VSwitch resource for interview."
# security parameters
group_name: "Security_Group_From_Demo"
group_description: "Create a new security group resource for interview."
group_inboundRules:
  - ip_protocol: tcp
    port_range: 22/22
    source_cidr_ip: 0.0.0.0/0
    priority: 1
# ecs parameters
image_id: ubuntu_18_04_x64_20G_alibase_20210420.vhd
instance_type: "ecs.n4.small"
instance_name: demo_for_interview_2021_05
instance_description: "demo for interview in 2021.05"
host_name: demo-interview
allocate_public_ip: True
password: Test123456
internet_charge_type: PayByTraffic
max_bandwidth_in: 200
max_bandwidth_out: 10
instance_tags: "demo=demo-interview"
system_disk_category: "cloud_ssd"
system_disk_size: 20
number_of_instances: 1
# nginx parameters
container_name: nginx
containter_image: nginx:stable
# security parameters
ssh_hardening_port: 22
nginx_external_port: 8989

